// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS05DA0wQoemXCp4DyiPs_oZPD4JQGpJw',
    appId: '1:552993149208:ios:2999afadb1b6631e170e6d',
    messagingSenderId: '552993149208',
    projectId: 'notifyme-59aae',
    storageBucket: 'notifyme-59aae.appspot.com',
    iosBundleId: 'com.example.notificationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkaDWbHMlFHPbPmllV5Jlw9WaoA-33Fno',
    appId: '1:552993149208:web:0f3845cd36e36aba170e6d',
    messagingSenderId: '552993149208',
    projectId: 'notifyme-59aae',
    authDomain: 'notifyme-59aae.firebaseapp.com',
    storageBucket: 'notifyme-59aae.appspot.com',
    measurementId: 'G-P28HYG1CEC',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkaDWbHMlFHPbPmllV5Jlw9WaoA-33Fno',
    appId: '1:552993149208:web:0f3845cd36e36aba170e6d',
    messagingSenderId: '552993149208',
    projectId: 'notifyme-59aae',
    authDomain: 'notifyme-59aae.firebaseapp.com',
    storageBucket: 'notifyme-59aae.appspot.com',
    measurementId: 'G-P28HYG1CEC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS05DA0wQoemXCp4DyiPs_oZPD4JQGpJw',
    appId: '1:552993149208:ios:2999afadb1b6631e170e6d',
    messagingSenderId: '552993149208',
    projectId: 'notifyme-59aae',
    storageBucket: 'notifyme-59aae.appspot.com',
    iosBundleId: 'com.example.notificationapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmU32r9IKvQ_AQqPpfnFGd92iyEwKcp2E',
    appId: '1:552993149208:android:96fdd84e6ae1430d170e6d',
    messagingSenderId: '552993149208',
    projectId: 'notifyme-59aae',
    storageBucket: 'notifyme-59aae.appspot.com',
  );

}